name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run Minecraft server simulation
        run: node minecraft-server.js

      - name: Run Aternos interaction script
        run: node aternos-interact.js
        env:
          API_KEY: ${{ secrets.ATERNOS_API_KEY }} # Store your Aternos API key in GitHub Secrets
