name: Build and Test

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Start server simulation
        run: |
          nohup node minecraft-server.js > server.log 2>&1 &
          sleep 10

      - name: Print runner IP address
        run: |
          echo "IP address of the GitHub Actions runner:"
          curl ifconfig.me

      - name: Run Aternos interaction script
        run: node aternos-interact.js
        env:
          ATERNOS_USERNAME: ${{ secrets.ATERNOS_USERNAME }}
          ATERNOS_PASSWORD: ${{ secrets.ATERNOS_PASSWORD }}

      - name: Verify server status
        run: |
          echo "Server is running and ready to test"
